# Blog info linxianlong
blog_name: Longlog.me
slogan: "Warning : Your time is fleeting."

# Set avatar (Absolute url and relative url)
#avatar: /images/avatar.jpg
avatar: /images/bayern.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: PHP,Golang,Python,JavaScript,后端开发

init_page_content: POST  # HOME_NAV | POST

home_nav:
  - name: Blog
    url: /archives
  - name: Github
    url: https://github.com/apeipo
    target: _blank

# config page nav
page_nav:
  - 首页: /
  - 分类: /categories/
  - 标签: /tags/
  - 友链: /link/
  - 关于: /about/
# - 2017: /2017/03/28/MY-2017/
# - 2018: /2018/08/06/2018-Target/
# - RSS: /atom.xml

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  verticalBoxShow: true

post:
  header_align: LEFT # LEFT|CENTER
  showToc: true # true|false

link:
  - name: Me
    info: Linxianlong
    url: http://longlog.me/
    avatar: https://avatars0.githubusercontent.com/u/6147812?v=3&s=460
  - name: forsigner
    info: theme author
    url: http://forsigner.com/
    avatar: https://avatars0.githubusercontent.com/u/2668081?v=3&s=460

about:
  - type: me
    icon: icon-user
    text_value:
    - "测试开发"
    - "2012.7 - 2015.3 @百度"
    - "2015.4 - Now    @滴滴"
    - "PHP / JavaScript / Python / Go."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@apeipo"
    text_value_url: https://github.com/apeipo
  - type: weibo
    text_key: 微博
    text_value: "@不鱼"
    text_value_url: http://weibo.com/u/2349219707
  - type: mail
    text_key: Gmail
    text_value: "apeipo@gmail.com"
  - type: location
    icon: icon-location
    text_value: 北京

# Stats
#google_analytics:
baidu_analytics: bec693dc99391bbe29dd7310e3fff81a

# Comment service
disqus_shortname: apeipo
# duoshuo_shortname: forsigner

# Custom CSS style
# personal_style: /css/forsigner.css

